# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('password_edit', models.CharField(max_length=36)),
                ('password_play', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardCategoryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('placement', models.IntegerField()),
                ('double_jeopardy', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('final_jeopardy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clue_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=50)),
                ('clue', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('placement', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='clues',
            field=models.ManyToManyField(to='jeopardy.Clue'),
        ),
        migrations.AddField(
            model_name='boardcategorymembership',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Category'),
        ),
        migrations.AddField(
            model_name='board',
            name='categories',
            field=models.ManyToManyField(related_name='board_categories', to='jeopardy.BoardCategoryMembership'),
        ),
        migrations.AddField(
            model_name='board',
            name='daily_doubles',
            field=models.ManyToManyField(to='jeopardy.Clue'),
        ),
    ]
