# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20170212_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='board_categories', to='jeopardy.BoardCategoryMembership'),
        ),
        migrations.AlterField(
            model_name='board',
            name='daily_doubles',
            field=models.ManyToManyField(blank=True, to='jeopardy.Clue'),
        ),
        migrations.AlterField(
            model_name='category',
            name='clues',
            field=models.ManyToManyField(blank=True, to='jeopardy.Clue'),
        ),
    ]
